version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:8080
    restart: unless-stopped
    
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    restart: unless-stopped
