name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  path-check:
    name: Path Check
    runs-on: ubuntu-latest
    outputs:
      eslint: ${{ steps.changes.outputs.eslint }}
      pylint: ${{ steps.changes.outputs.pylint }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2
      id: changes
      with:
        filters: |
          eslint:
            - 'frontend/**'
          pylint:
            - 'backend/**'
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: path-check
    if: ${{ needs.path-check.outputs.eslint == 'true' }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Eslint
        working-directory: ./frontend
        run: npm run lint
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    needs: path-check
    if: ${{ needs.path-check.outputs.pylint == 'true' }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python version
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Pylint
        working-directory: ./backend
        run: |
          pylint $(git ls-files '*.py')
