# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - simple-todolist-backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deactivate_deployments:
    runs-on: ubuntu-latest
    name: Deactivate Previous Deployments
    permissions:
      deployments: write
    steps:
      - name: Set Previous Deployements To Inactive
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Production - Backend
          onlyDeactivateDeployments: true

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python version
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        working-directory: ./backend
        run: zip ../release.zip ./* -r -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production - Backend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACBCD1AD1787421DB5F7670548F0C5E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_24E33D13451B42C9B6B2AF0BA1F5E138 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F8FB15C62D2F4511BC43694BF26E7AA1 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@2fdd5c3ebb4e540834e86ecc1f6fdcd5539023ee # v3
        id: deploy-to-webapp
        with:
          app-name: 'simple-todolist-backend'
          slot-name: 'Production'
          package: release.zip
          restart: true
