name: Restart Azure App Service - simple-todolist-backend

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  restart:
    name: Restart
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Login to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACBCD1AD1787421DB5F7670548F0C5E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_24E33D13451B42C9B6B2AF0BA1F5E138 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F8FB15C62D2F4511BC43694BF26E7AA1 }}

      - name: 'Restart Azure App Service'
        run: |
          az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Logout from Azure
        run: az logout
